server:
  port: 8002
spring:
  application:
    name: service-oss
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        #nacos注册中心服务地址
        server-addr: 127.0.0.1:8848

#阿里云 OSS
#不同的服务器，地址不同
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid:  your keyid
      keysecret:  your keysecret
      #bucket可以在控制台创建，也可以使用java代码创建
      bucketname: gl-edu  #your bucket
